# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/nniro/OneDrive/Desktop/Neaz/project_123/project_123.srcs/sources_1/bd/design_uart/ip/design_uart_ilmb_bram_if_cntlr_1/design_uart_ilmb_bram_if_cntlr_1.xci
# IP: The module: 'design_uart_ilmb_bram_if_cntlr_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nniro/OneDrive/Desktop/Neaz/project_123/project_123.gen/sources_1/bd/design_uart/ip/design_uart_ilmb_bram_if_cntlr_1/design_uart_ilmb_bram_if_cntlr_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_uart_ilmb_bram_if_cntlr_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/nniro/OneDrive/Desktop/Neaz/project_123/project_123.srcs/sources_1/bd/design_uart/ip/design_uart_ilmb_bram_if_cntlr_1/design_uart_ilmb_bram_if_cntlr_1.xci
# IP: The module: 'design_uart_ilmb_bram_if_cntlr_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nniro/OneDrive/Desktop/Neaz/project_123/project_123.gen/sources_1/bd/design_uart/ip/design_uart_ilmb_bram_if_cntlr_1/design_uart_ilmb_bram_if_cntlr_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_uart_ilmb_bram_if_cntlr_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
