# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_uart/design_uart.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_uart || ORIG_REF_NAME==design_uart} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_microblaze_0_0/design_uart_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_uart_microblaze_0_0 || ORIG_REF_NAME==design_uart_microblaze_0_0} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_dlmb_v10_1/design_uart_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_uart_dlmb_v10_1 || ORIG_REF_NAME==design_uart_dlmb_v10_1} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_ilmb_v10_1/design_uart_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_uart_ilmb_v10_1 || ORIG_REF_NAME==design_uart_ilmb_v10_1} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_dlmb_bram_if_cntlr_1/design_uart_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_uart_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==design_uart_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_ilmb_bram_if_cntlr_1/design_uart_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_uart_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==design_uart_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_lmb_bram_1/design_uart_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_uart_lmb_bram_1 || ORIG_REF_NAME==design_uart_lmb_bram_1} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_xbar_1/design_uart_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_uart_xbar_1 || ORIG_REF_NAME==design_uart_xbar_1} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_microblaze_0_axi_periph_1/design_uart_microblaze_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_uart_microblaze_0_axi_periph_1 || ORIG_REF_NAME==design_uart_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_microblaze_0_axi_intc_1/design_uart_microblaze_0_axi_intc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_uart_microblaze_0_axi_intc_1 || ORIG_REF_NAME==design_uart_microblaze_0_axi_intc_1} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_microblaze_0_xlconcat_1/design_uart_microblaze_0_xlconcat_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_uart_microblaze_0_xlconcat_1 || ORIG_REF_NAME==design_uart_microblaze_0_xlconcat_1} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_mdm_1_1/design_uart_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_uart_mdm_1_1 || ORIG_REF_NAME==design_uart_mdm_1_1} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_clk_wiz_1_1/design_uart_clk_wiz_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_uart_clk_wiz_1_1 || ORIG_REF_NAME==design_uart_clk_wiz_1_1} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_rst_clk_wiz_1_100M_1/design_uart_rst_clk_wiz_1_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_uart_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==design_uart_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_axi_uartlite_0_0/design_uart_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_uart_axi_uartlite_0_0 || ORIG_REF_NAME==design_uart_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_axi_gpio_0_0/design_uart_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_uart_axi_gpio_0_0 || ORIG_REF_NAME==design_uart_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_axi_timer_0_0/design_uart_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_uart_axi_timer_0_0 || ORIG_REF_NAME==design_uart_axi_timer_0_0} -quiet] -quiet

# IP: bd/design_uart/ip/design_uart_axi_gpio_1_0/design_uart_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_uart_axi_gpio_1_0 || ORIG_REF_NAME==design_uart_axi_gpio_1_0} -quiet] -quiet

# XDC: c:/Users/nniro/OneDrive/Desktop/Neaz/project_123/project_123.gen/sources_1/bd/design_uart/design_uart_ooc.xdc
